// status of each api call
export const FETCHING_API_START = "FETCHING_API_START";
export const FETCHING_API_SUCCESS = "FETCHING_API_SUCCESS";
export const FETCHING_API_FAILURE = "FETCHING_API_FAILURE";
export const FETCHING_SEARCH_VALUE = "FETCHING_SEARCH_VALUE";
export const SEARCH_VALUE = "SEARCH_VALUE";